// export const MLB_TEAMS_ARRAY = [
//   {"Name": "Diamondbacks", "City": "Arizona", "Symbol": "ARI"},
//   {"Name": "Braves", "City": "Atlanta", "Symbol": "ATL"},
//   {"Name": "Orioles", "City": "Baltimore", "Symbol": "BAL"},
//   {"Name": "Red Sox", "City": "Boston", "Symbol": "BOS"},
//   {"Name": "Cubs", "City": "Chicago", "Symbol": "CHC"},
//   {"Name": "White Sox", "City": "Chicago", "Symbol": "CHW"},
//   {"Name": "Reds", "City": "Cincinnati", "Symbol": "CIN"},
//   {"Name": "Indians", "City": "Cleveland", "Symbol": "CLE"},
//   {"Name": "Rockies", "City": "Colorado", "Symbol": "COL"},
//   {"Name": "Tigers", "City": "Detroit", "Symbol": "DET"},
//   {"Name": "Astros", "City": "Houston", "Symbol": "HOU"},
//   {"Name": "Royals", "City": "Kansas City", "Symbol": "KC"},
//   {"Name": "Angels", "City": "Los Angeles", "Symbol": "LAA"},
//   {"Name": "Dodgers", "City": "Los Angeles", "Symbol": "LAD"},
//   {"Name": "Marlins", "City": "Miami", "Symbol": "MIA"},
//   {"Name": "Brewers", "City": "Milwaukee", "Symbol": "MIL"},
//   {"Name": "Twins", "City": "Minnesota", "Symbol": "MIN"},
//   {"Name": "Mets", "City": "New York", "Symbol": "NYM"},
//   {"Name": "Yankees", "City": "New York", "Symbol": "NYY"},
//   {"Name": "Athletics", "City": "Oakland", "Symbol": "OAK"},
//   {"Name": "Phillies", "City": "Philadelphia", "Symbol": "PHI"},
//   {"Name": "Pirates", "City": "Pittsburgh", "Symbol": "PIT"},
//   {"Name": "Padres", "City": "San Diego", "Symbol": "SD"},
//   {"Name": "Giants", "City": "San Francisco", "Symbol": "SF"},
//   {"Name": "Mariners", "City": "Seattle", "Symbol": "SEA"},
//   {"Name": "Cardinals", "City": "St. Louis", "Symbol": "STL"},
//   {"Name": "Rays", "City": "Tampa Bay", "Symbol": "TB"},
//   {"Name": "Rangers", "City": "Texas", "Symbol": "TEX"},
//   {"Name": "Blue Jays", "City": "Toronto", "Symbol": "TOR"},
//   {"Name": "Nationals", "City": "Washington", "Symbol": "WSH"}
// ]

export const MLB_TEAMS_DICT =
  {
      'Diamondbacks': {'City': 'Arizona', 'Symbol': 'ARI'},
      'Braves': {'City': 'Atlanta', 'Symbol': 'ATL'},
      'Orioles': {'City': 'Baltimore', 'Symbol': 'BAL'},
      'Red Sox': {'City': 'Boston', 'Symbol': 'BOS'},
      'Cubs': {'City': 'Chicago', 'Symbol': 'CHC'},
      'White Sox': {'City': 'Chicago', 'Symbol': 'CHW'},
      'Reds': {'City': 'Cincinnati', 'Symbol': 'CIN'},
      'Indians': {'City': 'Cleveland', 'Symbol': 'CLE'},
      'Rockies': {'City': 'Colorado', 'Symbol': 'COL'},
      'Tigers': {'City': 'Detroit', 'Symbol': 'DET'},
      'Astros': {'City': 'Houston', 'Symbol': 'HOU'},
      'Royals': {'City': 'Kansas City', 'Symbol': 'KC'},
      'Angels': {'City': 'Los Angeles', 'Symbol': 'LAA'},
      'Dodgers': {'City': 'Los Angeles', 'Symbol': 'LAD'},
      'Marlins': {'City': 'Miami', 'Symbol': 'MIA'},
      'Brewers': {'City': 'Milwaukee', 'Symbol': 'MIL'},
      'Twins': {'City': 'Minnesota', 'Symbol': 'MIN'},
      'Mets': {'City': 'New York', 'Symbol': 'NYM'},
      'Yankees': {'City': 'New York', 'Symbol': 'NYY'},
      'Athletics': {'City': 'Oakland', 'Symbol': 'OAK'},
      'Phillies': {'City': 'Philadelphia', 'Symbol': 'PHI'},
      'Pirates': {'City': 'Pittsburgh', 'Symbol': 'PIT'},
      'Padres': {'City': 'San Diego', 'Symbol': 'SD'},
      'Giants': {'City': 'San Francisco', 'Symbol': 'SF'},
      'Mariners': {'City': 'Seattle', 'Symbol': 'SEA'},
      'Cardinals': {'City': 'St. Louis', 'Symbol': 'STL'},
      'Rays': {'City': 'Tampa Bay', 'Symbol': 'TB'},
      'Rangers': {'City': 'Texas', 'Symbol': 'TEX'},
      'Blue Jays': {'City': 'Toronto', 'Symbol': 'TOR'},
      'Nationals': {'City': 'Washington', 'Symbol': 'WSH'}
  }


