export const teams = [
  {"Name": "Diamondbacks", "City": "Arizona", "Symbol": "ARI"},
  {"Name": "Braves", "City": "Atlanta", "Symbol": "ATL"},
  {"Name": "Orioles", "City": "Baltimore", "Symbol": "BAL"},
  {"Name": "Red Sox", "City": "Boston", "Symbol": "BOS"},
  {"Name": "Cubs", "City": "Chicago", "Symbol": "CHC"},
  {"Name": "White Sox", "City": "Chicago", "Symbol": "CHW"},
  {"Name": "Reds", "City": "Cincinnati", "Symbol": "CIN"},
  {"Name": "Indians", "City": "Cleveland", "Symbol": "CLE"},
  {"Name": "Rockies", "City": "Colorado", "Symbol": "COL"},
  {"Name": "Tigers", "City": "Detroit", "Symbol": "DET"},
  {"Name": "Astros", "City": "Houston", "Symbol": "HOU"},
  {"Name": "Royals", "City": "Kansas City", "Symbol": "KC"},
  {"Name": "Angels", "City": "Los Angeles", "Symbol": "LAA"},
  {"Name": "Dodgers", "City": "Los Angeles", "Symbol": "LAD"},
  {"Name": "Marlins", "City": "Miami", "Symbol": "MIA"},
  {"Name": "Brewers", "City": "Milwaukee", "Symbol": "MIL"},
  {"Name": "Twins", "City": "Minnesota", "Symbol": "MIN"},
  {"Name": "Mets", "City": "New York", "Symbol": "NYM"},
  {"Name": "Yankees", "City": "New York", "Symbol": "NYY"},
  {"Name": "Athletics", "City": "Oakland", "Symbol": "OAK"},
  {"Name": "Phillies", "City": "Philadelphia", "Symbol": "PHI"},
  {"Name": "Pirates", "City": "Pittsburgh", "Symbol": "PIT"},
  {"Name": "Padres", "City": "San Diego", "Symbol": "SD"},
  {"Name": "Giants", "City": "San Francisco", "Symbol": "SF"},
  {"Name": "Mariners", "City": "Seattle", "Symbol": "SEA"},
  {"Name": "Cardinals", "City": "St. Louis", "Symbol": "STL"},
  {"Name": "Rays", "City": "Tampa Bay", "Symbol": "TB"},
  {"Name": "Rangers", "City": "Texas", "Symbol": "TEX"},
  {"Name": "Blue Jays", "City": "Toronto", "Symbol": "TOR"},
  {"Name": "Nationals", "City": "Washington", "Symbol": "WSH"}
]
